name: Release with Assets

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            assets/images/*.png
            assets/images/*.svg
